### ISSUE TITLE
Unsupported on macOS Sierra

### ISSUE THREAD

**Issue by JMY1000** [voidref/orangered#6]
App returns the following upon launch on macOS Sierra before exiting:
`objc[1443]: Objective-C garbage collection is no longer supported.`

**Comment by voidref** [comment]
Which binary are you using? 

You should be using this release:
https://github.com/voidref/orangered/releases

What's interesting is the app has never used garbage collection.

**Comment by JMY1000** [comment]
Apparently a very old version. Oops.
