### ISSUE TITLE
Not compatibile with macOS High Sierra / 10.13.6

### ISSUE THREAD

**Issue by sammcj** [voidref/orangered#8]
Was quite surprised to see this, what is it - 16bit or something? (just kidding).

![screen shot 2018-07-17 at 8 21 49 am](https://user-images.githubusercontent.com/862951/42786733-8ea1bbce-899a-11e8-9acc-9c6f4b7bff38.jpg)

I'll try recompiling the source but we'll see.

**Comment by voidref** [comment]
Merged sammcj's PR that fixes these issues.
